/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AudioEnhancementSettings {
  'noiseReductionLevel' : bigint,
  'pitchShiftSemitones' : bigint,
  'reverbRemovalLevel' : bigint,
  'voiceClarityLevel' : bigint,
  'deEsserLevel' : bigint,
  'eqBands' : [bigint, bigint, bigint],
}
export interface ExportJob {
  'id' : bigint,
  'status' : ExportStatus,
  'owner' : Principal,
  'projectId' : bigint,
  'outputFile' : [] | [ExternalBlob],
}
export type ExportStatus = { 'pending' : null } |
  { 'done' : null } |
  { 'processing' : null };
export type ExternalBlob = Uint8Array;
export type ProjectId = bigint;
export type Timestamp = bigint;
export interface TrackClip {
  'startTime' : bigint,
  'duration' : bigint,
  'trackType' : TrackType,
  'clipLabel' : string,
}
export type TrackType = { 'sfx' : null } |
  { 'music' : null } |
  { 'video' : null } |
  { 'dialogue' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoEditorProject {
  'id' : ProjectId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'audioSettings' : AudioEnhancementSettings,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTrackClip' : ActorMethod<[ProjectId, TrackClip], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createExportJob' : ActorMethod<[ProjectId], bigint>,
  'createProject' : ActorMethod<[string, string], ProjectId>,
  'deleteProject' : ActorMethod<[ProjectId], undefined>,
  'getAllProjects' : ActorMethod<[], Array<VideoEditorProject>>,
  'getAudioSettings' : ActorMethod<
    [ProjectId],
    [] | [AudioEnhancementSettings]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExportJob' : ActorMethod<[bigint], [] | [ExportJob]>,
  'getProject' : ActorMethod<[ProjectId], [] | [VideoEditorProject]>,
  'getProjectsOrderedByName' : ActorMethod<[], Array<VideoEditorProject>>,
  'getTrackClips' : ActorMethod<[ProjectId], Array<TrackClip>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeTrackClip' : ActorMethod<[ProjectId, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setExportJobOutputFile' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'updateAudioSettings' : ActorMethod<
    [ProjectId, AudioEnhancementSettings],
    undefined
  >,
  'updateExportJobStatus' : ActorMethod<[bigint, ExportStatus], undefined>,
  'updateProject' : ActorMethod<[ProjectId, VideoEditorProject], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];