/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProjectId = IDL.Nat;
export const TrackType = IDL.Variant({
  'sfx' : IDL.Null,
  'music' : IDL.Null,
  'video' : IDL.Null,
  'dialogue' : IDL.Null,
});
export const TrackClip = IDL.Record({
  'startTime' : IDL.Nat,
  'duration' : IDL.Nat,
  'trackType' : TrackType,
  'clipLabel' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const AudioEnhancementSettings = IDL.Record({
  'noiseReductionLevel' : IDL.Nat,
  'pitchShiftSemitones' : IDL.Int,
  'reverbRemovalLevel' : IDL.Nat,
  'voiceClarityLevel' : IDL.Nat,
  'deEsserLevel' : IDL.Nat,
  'eqBands' : IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat),
});
export const VideoEditorProject = IDL.Record({
  'id' : ProjectId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'audioSettings' : AudioEnhancementSettings,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExportStatus = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
  'processing' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ExportJob = IDL.Record({
  'id' : IDL.Nat,
  'status' : ExportStatus,
  'owner' : IDL.Principal,
  'projectId' : IDL.Nat,
  'outputFile' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTrackClip' : IDL.Func([ProjectId, TrackClip], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExportJob' : IDL.Func([ProjectId], [IDL.Nat], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text], [ProjectId], []),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(VideoEditorProject)], ['query']),
  'getAudioSettings' : IDL.Func(
      [ProjectId],
      [IDL.Opt(AudioEnhancementSettings)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExportJob' : IDL.Func([IDL.Nat], [IDL.Opt(ExportJob)], ['query']),
  'getProject' : IDL.Func(
      [ProjectId],
      [IDL.Opt(VideoEditorProject)],
      ['query'],
    ),
  'getProjectsOrderedByName' : IDL.Func(
      [],
      [IDL.Vec(VideoEditorProject)],
      ['query'],
    ),
  'getTrackClips' : IDL.Func([ProjectId], [IDL.Vec(TrackClip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeTrackClip' : IDL.Func([ProjectId, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setExportJobOutputFile' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'updateAudioSettings' : IDL.Func(
      [ProjectId, AudioEnhancementSettings],
      [],
      [],
    ),
  'updateExportJobStatus' : IDL.Func([IDL.Nat, ExportStatus], [], []),
  'updateProject' : IDL.Func([ProjectId, VideoEditorProject], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProjectId = IDL.Nat;
  const TrackType = IDL.Variant({
    'sfx' : IDL.Null,
    'music' : IDL.Null,
    'video' : IDL.Null,
    'dialogue' : IDL.Null,
  });
  const TrackClip = IDL.Record({
    'startTime' : IDL.Nat,
    'duration' : IDL.Nat,
    'trackType' : TrackType,
    'clipLabel' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const AudioEnhancementSettings = IDL.Record({
    'noiseReductionLevel' : IDL.Nat,
    'pitchShiftSemitones' : IDL.Int,
    'reverbRemovalLevel' : IDL.Nat,
    'voiceClarityLevel' : IDL.Nat,
    'deEsserLevel' : IDL.Nat,
    'eqBands' : IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat),
  });
  const VideoEditorProject = IDL.Record({
    'id' : ProjectId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'audioSettings' : AudioEnhancementSettings,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExportStatus = IDL.Variant({
    'pending' : IDL.Null,
    'done' : IDL.Null,
    'processing' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ExportJob = IDL.Record({
    'id' : IDL.Nat,
    'status' : ExportStatus,
    'owner' : IDL.Principal,
    'projectId' : IDL.Nat,
    'outputFile' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTrackClip' : IDL.Func([ProjectId, TrackClip], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExportJob' : IDL.Func([ProjectId], [IDL.Nat], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text], [ProjectId], []),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(VideoEditorProject)], ['query']),
    'getAudioSettings' : IDL.Func(
        [ProjectId],
        [IDL.Opt(AudioEnhancementSettings)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExportJob' : IDL.Func([IDL.Nat], [IDL.Opt(ExportJob)], ['query']),
    'getProject' : IDL.Func(
        [ProjectId],
        [IDL.Opt(VideoEditorProject)],
        ['query'],
      ),
    'getProjectsOrderedByName' : IDL.Func(
        [],
        [IDL.Vec(VideoEditorProject)],
        ['query'],
      ),
    'getTrackClips' : IDL.Func([ProjectId], [IDL.Vec(TrackClip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeTrackClip' : IDL.Func([ProjectId, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setExportJobOutputFile' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'updateAudioSettings' : IDL.Func(
        [ProjectId, AudioEnhancementSettings],
        [],
        [],
      ),
    'updateExportJobStatus' : IDL.Func([IDL.Nat, ExportStatus], [], []),
    'updateProject' : IDL.Func([ProjectId, VideoEditorProject], [], []),
  });
};

export const init = ({ IDL }) => { return []; };